export const GET_GIF = 'GET_GIF'
export const SEARCH_GIF = 'SEARCH_GIF'
export const ADD_GIF = 'ADD_GIF'
export const REMOVE_GIF = 'REMOVE_GIF'
export const SET_GIF = 'SET_GIF'
export const SET_SEARCH_GIF = 'SET_SEARCH_GIF'